---
- name: Configure web VMs with metricbeat
  hosts: dvwa
  become: true
  tasks:
    - name: download metricbeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install metricbeat
      ansible.builtin.dpkg_selections:
        name: metricbeat-7.6.1-amd64.deb
        selection: install

    - name: copy confs
      copy:
        src: /etc/ansible/Files/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable and configure docker
      command: metricbeat modules enable docker

    - name: setup metricbeat
      command: metricbeat setup

    - name: enable metricbeat
      service:
        name: metricbeat
        enabled: yes
        state: started